//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaFINAKTIVA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MunicipalityRegion
    {
        public int MunicipalyRegionId { get; set; }
        public int MunicipalityId { get; set; }
        public int RegionId { get; set; }
    
        public virtual Municipalitys Municipalitys { get; set; }
        public virtual Region Region { get; set; }
    }
}
