//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaFINAKTIVA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipios
    {
        public int codigo_mupio { get; set; }
        public string nombre_mupio { get; set; }
        public bool estado { get; set; }
        public int codigo_region { get; set; }
    
        public virtual regiones regiones { get; set; }
    }
}
